### ISSUE TITLE
API: Update for dataset_description

### ISSUE THREAD

**Issue by LIN810116** [SPARC-FAIR-Codeathon/sparc-me#87]
- Refactoring. e.g. rename/update `set_field` to add_value/add_values
- Removing the need to specify row for dataset_descriptions metadata

Describing the dataset
```
dataset.list_elements()
dataset_description = dataset.get_category()
values = [“bob, builder”]
dataset_description.add_values(“element_name_string”, values)
dataset_description.remove_values(“element_name_string”, value)
dataset_description.clear_values(“field_string”)
values = dataset_description.get_values(“field_string”)
```

**Comment by LinkunGao** [comment]
For Tu2 steps:

1.  create dataset from template
2.  save the dataset template
3. add data to dataset template
4. edit dataset metadata
   - description_metadata values: CRUD
   -

**Comment by LinkunGao** [comment]
Developed a MetadataEditor class for editing all metadata files(code_description, code_parameters, dataset_description, manifest, performances, resources, samples, subjects, submission). we can use MetadataEditor  to edit all of them at the same time with these functions:

- `metadataEditor.add_values(*values, field_name='', header='', append=False)`

    - this function can accept multiple values for each rows or cols.
    - for the code_description and dataset_description we probably want set values by each rows, and start a Value column, so we can set the row name for field_name, ana the default value for header is Value column (you also can set others if you like) . `metadataEditor.add_values(*values, field_name='contributor role')`
    - in terms of others metadata files, we can set the values for them by rows or by each columns:
       - by rows: we can create a value list for that metadata file by `metadataEditor.add_values(*values)`, in this way we don't need to consider the field name and header name. if we want add more rows values, we need set append = True. Then you can recall this function again. the second value list will be added into the next row.
       - by each columns: we also can create  a value list for metadata files by their column header name. In this way, we can add values for a specific header, we can also choose to if append values or not. `metadataEditor.add_values(*values, header='name', append=True)`
- `metadataEditor.get_values(field_name)`
   - as for the   `code_description and dataset_description`  files, we need to provide the row name to get the values of that row.
   - others, we need to specify the header name to get all values of that column
- `metadataEditor.remove_values(*values, field_name)`
   - prepare the remove_value list for the specific row or col
   - as for the   `code_description and dataset_description`  files, we need to set the row name for the field_name
   - in terms of others, we need to set header name for field_name
- `metadataEditor.clear_values(field_name='')`
   - if we don't provide the field_name, this function will reset the entire file to the default status.
   - same as before, for the   code_description and dataset_description  files, we can provide the row name for field name to reset the values in that row to default status.
   - others, we can provide the header/column name.
- validate function for entire MetadataEditor:
   - I also developed a function to validate user inputs for the header/row_name/elements names typing. it can ignore the Case and white space. E.g: if we want use `Contributor name`  row_name, we can ignore user types like this `Contributor name`, `Contributor Name` ,`CONtributor naMe` , `contributorname` .etc, these inputs are all match the `Contributor Name` .
